### ISSUE TITLE
Using Adafruit RP2040 board as Greaseweazle

### ISSUE THREAD

**Issue by AdamKeher** [RobSmithDev/DiskFlashback#1]
Hi, great project!

How are you detecting the Greaseweazle board? It doesn't recognise the rp2040 greaseweazle boards.

Board is reported as:

PS C:\Users\adamk\Downloads\greaseweazle-1.16.3> .\gw.exe info --device COM5
Host Tools: 1.16.3
Device:
  Port:     COM5
  Model:    Adafruit Floppy Generic
  Firmware: 1.0
  Serial:   DF6254209F914F2D
  USB:      Full Speed (12 Mbit/s)

**Comment by RobSmithDev** [comment]
Hi, I was aware of the Adifruit boards but didnt realise they were Greaseweazle compatible. The software performs the following to auto-detect boards:

1. VID/PID (vid=0x1209, pid=0x4d69)
2. Looks to see if the "Product Name" is "Greaseweazle"
3. Looks to see if its mounted as "\GW"
If any of those match it will be picked up as a possible auto-detection port.

My guess is it doesnt identify as any of these, so I'll need to figure out how it does identify so it can be supported.

**Comment by RobSmithDev** [comment]
So just flashed the firmware to a RP2040 and appears as "TinyUSB Serial" with different PID/VID numbers so totally different.

I've noticed there was a bug where turning off the Auto Detect Com Port doesnt actually work, will be fixed in the next version which woudl have been the suggested work-around....

However, The Adafruit greaseweazle firmware **doesnt support** the _GetPin_ command for _Write Protect_ or _Disk Change_, which is required, so won't work anyway unless their update their firmware.

**Comment by AdamKeher** [comment]
I forked their firmware and modified it to support the

**Comment by AdamKeher** [comment]
I forked the project and modified the GreaseWeazel code to support these GetPin commands. It required the latest adafruit_floppy library from GitHub rather than the one available in the Library Manager repository. The newer adafruit_floppy library supports the get_ready_sense() method.

I tried it with your FloppyDriveBridge and it sees the device, gets through the openInterface and clicks the drive at kickstart. When a disk is inserted it turns the motor on and tries to read but fails. I didn't trace it any further though.

fork: https://github.com/AdamKeher/Adafruit_Floppy

The GreaseWeazel code identifies it with the GW_HW_MODEL = 8
